name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
   IMAGE_NAME: ptr-test
   IMAGE_TAGS: v1 ${{ github.sha }}
   IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
   REGISTRY_USER: ${{ github.actor }}
   REGISTRY_PASSWORD: ${{ github.token }}

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/login-action@v3
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)




   # - name: Push To GHCR
   #   uses: ./
   #   id: push
   #   with:
   #     image: ${{ steps.build_image.outputs.image }}
   #     tags: ${{ steps.build_image.outputs.tags }}
   #     registry: ${{ env.IMAGE_REGISTRY }}
   #     username: ${{ env.REGISTRY_USER }}
   #     password: ${{ env.REGISTRY_PASSWORD }}
   #     extra-args: |
   #       --disable-content-trust
